scrape_configs:
  - job_name: 'redis-cache-demo'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Redis Cache Demo'